apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magento2-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/company/magento2-gitops.git'
    targetRevision: HEAD
    path: helm/magento
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: magento-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
