apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  MYSQL_USER: "magento"
  MYSQL_PASSWORD: "MagentoSecretDbPassword123!"
  RABBITMQ_USER: "magento"
  RABBITMQ_PASSWORD: "RabbitSecretPassword123!"
